export const RETRY_STATUS_CODES = [408, 425, 429, 500, 502, 503, 504];
export const RETRY_ERROR_CODES = [
    'ENOTFOUND',
    'ECONNREFUSED',
    'ECONNRESET',
    'ETIMEDOUT',
    'EPIPE',
    'EAI_AGAIN',
    'EHOSTDOWN',
    'EHOSTUNREACH',
    'ENETDOWN',
    'ENETRESET',
    'ENETUNREACH',
    'ECONNABORTED'
];
